# Generated by Django 6.0.6 on 2026-06-19 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('kolor', models.CharField(max_length=30)),
                ('cena_za_szpule', models.DecimalField(decimal_places=2, max_digits=6)),
                ('waga_poczatkowa', models.IntegerField(default=1000)),
                ('waga_aktualna', models.IntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Zlecenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_detalu', models.CharField(max_length=100)),
                ('zuzycie_glowny_g', models.IntegerField(verbose_name='Zużycie główne (g)')),
                ('zuzycie_dodatkowy_g', models.IntegerField(blank=True, default=0, null=True, verbose_name='Zużycie dodatkowe (g)')),
                ('czas_druku_minuty', models.IntegerField()),
                ('status', models.CharField(choices=[('OCZEKUJACE', 'Oczekujące'), ('W_TRAKCIE', 'W trakcie druku'), ('ZAKONCZONE', 'Zakończone'), ('ANULOWANE', 'Anulowane')], default='OCZEKUJACE', max_length=15)),
                ('koszt_calkowity', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('filament_dodatkowy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zlecenia_dodatkowe', to='zlecenia.filament', verbose_name='Filament dodatkowy (opcja)')),
                ('filament_glowny', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zlecenia_glowne', to='zlecenia.filament')),
            ],
        ),
    ]
