# Generated by Django 6.0.6 on 2026-06-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zlecenia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filament',
            name='kolor',
            field=models.CharField(choices=[('#000000', 'Czarny'), ('#FFFFFF', 'Biały'), ('#FF0000', 'Czerwony'), ('#0000FF', 'Niebieski'), ('#00FF00', 'Zielony'), ('#FFFF00', 'Żółty'), ('#FFA500', 'Pomarańczowy'), ('#808080', 'Szary'), ('#FFD700', 'Złoty'), ('#C0C0C0', 'Srebrny'), ('#8B4513', 'Brązowy'), ('#FF69B4', 'Różowy')], default='#000000', max_length=7),
        ),
    ]
